# docker-compose.yml
version: "3"
services:
  server:
    build: server
    depends_on:
      - postgres
    ports:
      - "4501:4501"
    working_dir: /server
    volumes:
        - ./server:/server
        - ./divabotguardian:/divabotguardian
        - /var/www/html/divar:/divabotguardian/www
    env_file:
        - ./server/.env.twitter
    logging:
      options:
        max-size: "1m"
        max-file: "3"

  server2:
    build: server2
    depends_on:
      - postgres
    ports:
      - "4504:4504"
    working_dir: /server2
    volumes:
        - ./server2:/server2
    env_file:
        - ./server/.env.twitter
    logging:
      options:
        max-size: "1m"
        max-file: "3"

        
  imgparser:
    build: imgparser
    restart: always
    ports:
      - "4503:4503"
    volumes:
        - ./imgparser:/imgparser
    working_dir: /imgparser/projectDivaImgParser
    logging:
      options:
        max-size: "1m"
        max-file: "3"

  postgres:
    image: postgres:10.4
    restart: always
    ports:
      - "4502:5432"
    volumes:
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: divar
    logging:
      options:
        max-size: "1m"
        max-file: "3"

  frontend:
    build: 
        context: frontend
        dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - postgres
      - server
    ports:
      - "80:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    working_dir: /frontend
    env_file:
        - ./frontend/.env
    volumes:
        - /app/node_modules
        - ./frontend:/frontend
    logging:
      options:
        max-size: "1m"
        max-file: "3"
        
      
#  prod-frontend:
#    build:
#      context: frontend
#      dockerfile: Dockerfile.prod
#    ports:
#      - '3004:80'