update songs set name=E'Catch the Wave',english_name=E'Catch the Wave',romanized_name=E'' where id=1;
update songs set name=E'エイリアンエイリアン',english_name=E'Alien Alien',romanized_name=E'Eirian eirian' where id=2;
update songs set name=E'39みゅーじっく！',english_name=E'39 Music!',romanized_name=E'39 myuujikku' where id=3;
update songs set name=E'どりーみんチュチュ',english_name=E'Dreamin Chuchu',romanized_name=E'Doriimin chu chu' where id=4;
update songs set name=E'ヒバナ',english_name=E'HIBANA',romanized_name=E'Hibana' where id=5;
update songs set name=E'大江戸ジュリアナイト',english_name=E'Ooedo Julia-Night',romanized_name=E'Ooedo juria naito' where id=6;
update songs set name=E'テオ',english_name=E'Teo',romanized_name=E'Teo' where id=7;
update songs set name=E'ジターバグ',english_name=E'JITTERBUG',romanized_name=E'Jitaabagu' where id=8;
update songs set name=E'ジグソーパズル',english_name=E'Jigsaw Puzzle',romanized_name=E'Jigusoo puzuru' where id=9;
update songs set name=E'ロキ',english_name=E'ROKI',romanized_name=E'Roki' where id=10;
update songs set name=E'ワールドイズマイン',english_name=E'The World is Mine',romanized_name=E'Waarudo izu main' where id=11;
update songs set name=E'メルト',english_name=E'Melt',romanized_name=E'Meruto' where id=12;
update songs set name=E'ミラクルペイント',english_name=E'Miracle Paint',romanized_name=E'Mirakuru peinto' where id=13;
update songs set name=E'桜ノ雨',english_name=E'Sakura no Ame',romanized_name=E'Sakura no ame' where id=14;
update songs set name=E'えれくとりっく・えんじぇぅ',english_name=E'Electric Angel',romanized_name=E'Erekutorikku enjeu' where id=15;
update songs set name=E'初音ミクの消失 -DEAD END-',english_name=E'The Disappearance of Hatsune Miku',romanized_name=E'Hatsune Miku no shoushitsu' where id=16;
update songs set name=E'みくみくにしてあげる♪',english_name=E'I\'ll Miku-Miku You♪ (For Reals)',romanized_name=E'Miku Miku ni shite ageru♪ (Shiteyanyo)' where id=17;
update songs set name=E'ロミオとシンデレラ',english_name=E'Romeo and Cinderella',romanized_name=E'Romio to shinderera' where id=18;
update songs set name=E'magnet',english_name=E'Magnet',romanized_name=E'magnet' where id=19;
update songs set name=E'愛言葉',english_name=E'Aikotoba',romanized_name=E'Ai kotoba' where id=20;
update songs set name=E'Just Be Friends',english_name=E'',romanized_name=E'Just Be Friends' where id=21;
update songs set name=E'from Y to Y',english_name=E'from Y to Y',romanized_name=E'' where id=22;
update songs set name=E'ぽっぴっぽー',english_name=E'Po Pi Po',romanized_name=E'Poppippoo' where id=23;
update songs set name=E'カンタレラ',english_name=E'Cantarella',romanized_name=E'Kandarera' where id=24;
update songs set name=E'ジェミニ',english_name=E'Gemini',romanized_name=E'Jemini' where id=25;
update songs set name=E'ハジメテノオト',english_name=E'The First Sound',romanized_name=E'Hajimete no oto' where id=26;
update songs set name=E'サイハテ',english_name=E'Saihate',romanized_name=E'Saihate' where id=27;
update songs set name=E'カラフル×メロディ',english_name=E'Colorful × Melody',romanized_name=E'Karafuru × Medodi' where id=28;
update songs set name=E'初音ミクの激唱',english_name=E'The Intense Voice of Hatsune Miku',romanized_name=E'Hatsune Miku no gekishou' where id=29;
update songs set name=E'Palette',english_name=E'Palette',romanized_name=E'' where id=30;
update songs set name=E'SPiCa -39\'s Giving Day Edition-',english_name=E'SPiCa',romanized_name=E'' where id=31;
update songs set name=E'番凩',english_name=E'Wintry Winds',romanized_name=E'Tsugai kogarashi' where id=32;
update songs set name=E'ルカルカ★ナイトフィーバー',english_name=E'Luka Luka★Night Fever',romanized_name=E'Ruka Ruka★naito feebaa' where id=33;
update songs set name=E'＊ハロー、プラネット。 (I.M.PLSE-EDIT)',english_name=E'*Hello, Planet.',romanized_name=E'*Haroo, puranetto.' where id=34;
update songs set name=E'裏表ラバーズ',english_name=E'Two-Sided Lovers',romanized_name=E'Ura-omote rabaazu' where id=35;
update songs set name=E'ローリンガール',english_name=E'Rolling Girl',romanized_name=E'Roorin gaaru' where id=36;
update songs set name=E'トリコロール・エア・ライン',english_name=E'Tricolore Airline',romanized_name=E'Torikorooru ea rain' where id=37;
update songs set name=E'on the rocks',english_name=E'On The Rocks',romanized_name=E'on the rocks' where id=38;
update songs set name=E'LOL -lots of laugh-',english_name=E'LOL -lots of laugh-',romanized_name=E'' where id=39;
update songs set name=E'深海少女',english_name=E'Deep Sea Girl',romanized_name=E'Shinkai shoujo' where id=40;
update songs set name=E'君の体温',english_name=E'Kimi no Taion',romanized_name=E'Kimi no taion' where id=41;
update songs set name=E'キャットフード',english_name=E'Cat Food',romanized_name=E'Kyatto fuudo' where id=42;
update songs set name=E'秘密警察',english_name=E'Secret Police',romanized_name=E'Himitsu keisatsu' where id=43;
update songs set name=E'メランコリック',english_name=E'Melancholic',romanized_name=E'Merankorikku' where id=44;
update songs set name=E'Weekender Girl',english_name=E'Weekender Girl',romanized_name=E'' where id=45;
update songs set name=E'タイムマシン',english_name=E'Time Machine',romanized_name=E'taimu mashin' where id=46;
update songs set name=E'DYE',english_name=E'DYE',romanized_name=E'' where id=47;
update songs set name=E'Fire◎Flower',english_name=E'Fire◎Flower',romanized_name=E'' where id=48;
update songs set name=E'ACUTE',english_name=E'ACUTE',romanized_name=E'' where id=49;
update songs set name=E'トリノコシティ',english_name=E'Torinoko City',romanized_name=E'Torinoko shidi' where id=50;
update songs set name=E'リモコン',english_name=E'',romanized_name=E'' where id=51;
update songs set name=E'FREELY TOMORROW',english_name=E'Freely Tomorrow',romanized_name=E'FREELY TOMORROW' where id=52;
update songs set name=E'モノクロ∞ブルースカイ',english_name=E'Monochrome∞Blue Sky',romanized_name=E'Monnokuro∞buruu sukai' where id=53;
update songs set name=E'ワールズエンド・ダンスホール',english_name=E'World\'s End Dance Hall',romanized_name=E'Waaruzuendo dansuhooru' where id=54;
update songs set name=E'ネトゲ廃人シュプレヒコール',english_name=E'The MMORPG Addict\'s Anthem',romanized_name=E'Netoge hijin shupurehikooru' where id=55;
update songs set name=E'Nostalogic',english_name=E'Nostalogic',romanized_name=E'' where id=56;
update songs set name=E'アンハッピーリフレイン',english_name=E'Unhappy Refrain',romanized_name=E'Anhapii refurein' where id=57;
update songs set name=E'ODDS&ENDS',english_name=E'Odds & Ends',romanized_name=E'ODDS&ENDS' where id=58;
update songs set name=E'天樂',english_name=E'Tengaku',romanized_name=E'Tengaku' where id=59;
update songs set name=E'ブラック★ロックシューター',english_name=E'Black★Rock Shooter',romanized_name=E'Burakku★rokku syuudaa' where id=60;
update songs set name=E'Sadistic.Music∞Factory',english_name=E'Sadistic.Music∞Factory',romanized_name=E'' where id=61;
update songs set name=E'Tell Your World',english_name=E'Tell Your World',romanized_name=E'' where id=62;
update songs set name=E'東京テディベア',english_name=E'Tokyo Teddy Bear',romanized_name=E'Tokyo tedi bea' where id=63;
update songs set name=E'Sweet Devil',english_name=E'Sweet Devil',romanized_name=E'' where id=64;
update songs set name=E'千本桜',english_name=E'Senbonzakura',romanized_name=E'Senbonzakura' where id=65;
update songs set name=E'スイートマジック',english_name=E'Sweet Magic',romanized_name=E'Suiito majiku' where id=66;
update songs set name=E'テレカクシ思春期',english_name=E'Terekakushi Shishunki',romanized_name=E'Terekakushi shishunki' where id=67;
update songs set name=E'アマツキツネ',english_name=E'Amatsu Kitsune',romanized_name=E'Amatsu kitsune' where id=68;
update songs set name=E'アゲアゲアゲイン',english_name=E'Ageage Again',romanized_name=E'Ageage again' where id=69;
update songs set name=E'1/6 -out of the gravity-',english_name=E'1/6 -out of the gravity-',romanized_name=E'' where id=70;
update songs set name=E'1925',english_name=E'1925',romanized_name=E'' where id=71;
update songs set name=E'サンドリヨン',english_name=E'Cendrillon',romanized_name=E'Sendoriyon' where id=72;
update songs set name=E'スノーマン',english_name=E'Snowman',romanized_name=E'Sunooman' where id=73;
update songs set name=E'骸骨楽団とリリア',english_name=E'Gaikotsu Gakudan to Riria',romanized_name=E'Gaikotsu gakudan to Riria' where id=74;
update songs set name=E'ありふれたせかいせいふく',english_name=E'Arifureta Sekai Seifuku',romanized_name=E'Arifureta sekai seifuku' where id=75;
update songs set name=E'インタビュア',english_name=E'Interviewer',romanized_name=E'Inkubya' where id=76;
update songs set name=E'ピアノ×フォルテ×スキャンダル',english_name=E'Piano × Forte × Scandal',romanized_name=E'Piano × Forute × Sukyandaru' where id=77;
update songs set name=E'shake it!',english_name=E'shake it!',romanized_name=E'' where id=78;
update songs set name=E'アカツキアライヴァル',english_name=E'Akatsuki Arrival',romanized_name=E'Akatsuki arrival' where id=79;
update songs set name=E'Glory 3usi9',english_name=E'Glory 3usi9',romanized_name=E'' where id=80;
update songs set name=E'スキキライ',english_name=E'Love-Hate',romanized_name=E'Suki kirai' where id=81;
update songs set name=E'指切り',english_name=E'Pinky Swear',romanized_name=E'Yubikiri' where id=82;
update songs set name=E'Blackjack',english_name=E'Blackjack',romanized_name=E'' where id=83;
update songs set name=E'からくりピエロ',english_name=E'Karakuri Pierrot',romanized_name=E'Karakuri pierot' where id=84;
update songs set name=E'なりすましゲンガー',english_name=E'Doubleganger',romanized_name=E'Narisumashi gengaa' where id=85;
update songs set name=E'こちら、幸福安心委員会です。',english_name=E'This is the Happiness and Peace of Mind Committee',romanized_name=E'Kochira, koufuku anshin iinkai desu.' where id=86;
update songs set name=E'Hello, Worker',english_name=E'Hello, Worker',romanized_name=E'' where id=87;
update songs set name=E'メテオ',english_name=E'Meteor',romanized_name=E'Meteo' where id=88;
update songs set name=E'soundless voice',english_name=E'Soundless Voice',romanized_name=E'souldless voice' where id=89;
update songs set name=E'erase or zero',english_name=E'Erase or Zero',romanized_name=E'erase or zero' where id=90;
update songs set name=E'エンヴィキャットウォーク',english_name=E'Envy Cat Walk',romanized_name=E'Enbi kyatto wooku' where id=91;
update songs set name=E'DECORATOR',english_name=E'Decorator',romanized_name=E'DECORATOR' where id=92;
update songs set name=E'二次元ドリームフィーバー',english_name=E'2D Dream Fever',romanized_name=E'Nijigen Doriimu fiibaa' where id=93;
update songs set name=E'はじめまして地球人さん',english_name=E'Nice To Meet You, Mr. Earthling',romanized_name=E'Hajimemashite Chikyuujin-san' where id=94;
update songs set name=E'Hand in Hand',english_name=E'Hand in Hand',romanized_name=E'' where id=95;
update songs set name=E'白い雪のプリンセスは',english_name=E'The Snow White Princess is..',romanized_name=E'Shiroi yuki no purinsesu wa' where id=96;
update songs set name=E'39',english_name=E'39',romanized_name=E'' where id=97;
update songs set name=E'ブラックゴールド',english_name=E'Black Gold',romanized_name=E'Burakku goorudo' where id=98;
update songs set name=E'ヒビカセ',english_name=E'Hibikase',romanized_name=E'Hibikase' where id=99;
update songs set name=E'ゴーストルール',english_name=E'Ghost Rule',romanized_name=E'Goosuto ruuru' where id=100;
update songs set name=E'砂の惑星',english_name=E'Suna no Wakusei feat. Hatsune Miku',romanized_name=E'Suna no wakusei feat. Hatsune Miku' where id=101;
update songs set name=E'The secret garden',english_name=E'The secret garden',romanized_name=E'' where id=102;
update songs set name=E'こっち向いて Baby',english_name=E'Look This Way, Baby',romanized_name=E'Kocchi muite Baby' where id=103;
update songs set name=E'積乱雲グラフィティ',english_name=E'Sekiranun Graffiti',romanized_name=E'Sekiranun gurafiti' where id=104;
update songs set name=E'ゆめゆめ',english_name=E'Yumeyume',romanized_name=E'Yume yume' where id=105;
update songs set name=E'結ンデ開イテ羅刹ト骸',english_name=E'Close and Open, Demons and The Dead',romanized_name=E'Musunde hiraite rasetsu to mukuro' where id=106;
update songs set name=E'エレクトロサチュレイタ',english_name=E'Electrosaturator',romanized_name=E'Erekutoro sachureita' where id=107;
update songs set name=E'炉心融解',english_name=E'Rushin Yukai',romanized_name=E'Roshin yuukai' where id=108;
update songs set name=E'ダブルラリアット',english_name=E'Double Lariat',romanized_name=E'Dapuru rariatto' where id=109;
update songs set name=E'ハイハハイニ',english_name=E'Ashes to Ashes',romanized_name=E'Hai wa hai ni' where id=110;
update songs set name=E'壊セ壊セ',english_name=E'Break It, Break It!',romanized_name=E'Kowase kowase' where id=111;
update songs set name=E'初めての恋が終わる時',english_name=E'When First Love Ends',romanized_name=E'Hajimete no hoi ga owaru toki' where id=112;
update songs set name=E'妄想スケッチ',english_name=E'Mousou Sketch',romanized_name=E'Mousou sketch' where id=113;
update songs set name=E'デンパラダイム',english_name=E'Denparadigm',romanized_name=E'Den paradaimu' where id=114;
update songs set name=E'孤独の果て -extend edition-',english_name=E'Solitude\'s End',romanized_name=E'Kodoku no hate' where id=115;
update songs set name=E'右肩の蝶',english_name=E'Butterfly on Your Right Shoulder',romanized_name=E'Migikata no chou' where id=116;
update songs set name=E'No Logic',english_name=E'No Logic',romanized_name=E'' where id=117;
update songs set name=E'え？あぁ、そう。',english_name=E'Hm? Ah, Yes.',romanized_name=E'E? Aa, sou.' where id=118;
update songs set name=E'packaged',english_name=E'Packaged',romanized_name=E'' where id=119;
update songs set name=E'巨大少女',english_name=E'Gigantic Girl',romanized_name=E'Kyodai shoujo' where id=120;
update songs set name=E'サマーアイドル',english_name=E'Summer Idol',romanized_name=E'Samaa aidoru' where id=121;
update songs set name=E'千年の独奏歌',english_name=E'Thousand Year Solo',romanized_name=E'Sennen no dokusou Ka' where id=122;
update songs set name=E'忘却心中',english_name=E'Lover\'s Suicide Oblivion',romanized_name=E'Boukyaku hinjuu' where id=123;
update songs set name=E'WORLD\'S END UMBRELLA',english_name=E'World\'s End Umbrella',romanized_name=E'WORLD\'S END UMBRELLA' where id=124;
update songs set name=E'恋スルVOC@LOID',english_name=E'VOC@LOID in Love',romanized_name=E'Koisuru VOC@LOID' where id=125;
update songs set name=E'神曲',english_name=E'God-Tier Tune',romanized_name=E'Kami kyoku' where id=126;
update songs set name=E'Yellow',english_name=E'Yellow',romanized_name=E'' where id=127;
update songs set name=E'ネガポジ＊コンティニューズ',english_name=E'Negaposi*Continues',romanized_name=E'Negapoji*kontinyuuzu' where id=128;
update songs set name=E'SING&SMILE',english_name=E'SING&SMILE',romanized_name=E'' where id=129;
update songs set name=E'歌に形はないけれど',english_name=E'Though My Song Has No Form',romanized_name=E'Uta ni katachi wa nai keredo' where id=130;
update songs set name=E'Dear',english_name=E'Dear',romanized_name=E'' where id=131;
update songs set name=E'どういうことなの！？',english_name=E'What Do You Mean!?',romanized_name=E'Dou iu koto na no!?' where id=132;
update songs set name=E'クローバー♣クラブ',english_name=E'Clover♣Club',romanized_name=E'kuroobaa kurapu' where id=133;
update songs set name=E'リンちゃんなう！',english_name=E'Rin-chan Now!',romanized_name=E'Rin-chan nau!' where id=134;
update songs set name=E'深海シティアンダーグラウンド',english_name=E'Deep Sea City Underground',romanized_name=E'Shinkai city andaaguraundo' where id=135;
update songs set name=E'二息歩行',english_name=E'Two Breaths Walking',romanized_name=E'Nisoku hokou' where id=136;
update songs set name=E'PIANO*GIRL',english_name=E'PIANO*GIRL',romanized_name=E'' where id=137;
update songs set name=E'システマティック・ラヴ',english_name=E'Systematic Love',romanized_name=E'Shisutematikku rabu' where id=138;
update songs set name=E'ココロ',english_name=E'Kokoro',romanized_name=E'' where id=139;
update songs set name=E'夢喰い白黒バク',english_name=E'Dream-Eating Monochrome Baku',romanized_name=E'Yumekui shirokuro baku' where id=140;
update songs set name=E'Knife',english_name=E'Knife',romanized_name=E'' where id=141;
update songs set name=E'ブレス・ユア・ブレス',english_name=E'Bless Your Breath',romanized_name=E'Buresu yua buresu' where id=142;
update songs set name=E'恋は戦争',english_name=E'Love is War',romanized_name=E'Koi wa sensou' where id=143;
update songs set name=E'あなたの歌姫',english_name=E'I\'m Your Diva',romanized_name=E'Anata no utahime' where id=144;
update songs set name=E'Starduster',english_name=E'Starduster',romanized_name=E'' where id=145;
update songs set name=E'StargazeR',english_name=E'StargazeR',romanized_name=E'' where id=146;
update songs set name=E'リンリンシグナル',english_name=E'RinRin Signal',romanized_name=E'Rin Rin shugynaru' where id=147;
update songs set name=E'Rosary Pale',english_name=E'Rosary Pale',romanized_name=E'' where id=148;
update songs set name=E'多重未来のカルテット～QUARTET THEME～',english_name=E'Quartet of Multiple Futures',romanized_name=E'Tajuu mirai no karudetto' where id=149;
update songs set name=E'LIKE THE WIND',english_name=E'LIKE THE WIND',romanized_name=E'' where id=150;
update songs set name=E'AFTER BURNER',english_name=E'AFTER BURNER',romanized_name=E'' where id=151;
update songs set name=E'ストロボナイツ',english_name=E'Strobe Nights',romanized_name=E'Sutorobo naito' where id=152;
update songs set name=E'VOiCE',english_name=E'VOiCE',romanized_name=E'' where id=153;
update songs set name=E'恋色病棟',english_name=E'Love-Colored Ward',romanized_name=E'Koi iro byoutou' where id=154;
update songs set name=E'ねこみみスイッチ',english_name=E'NekoMimi Switch',romanized_name=E'Nekomimi suicchi' where id=155;
update songs set name=E'パラジクロロベンゼン',english_name=E'Paradichlorobenzene',romanized_name=E'Parajikurorobenzen' where id=156;
update songs set name=E'カラフル×セクシィ',english_name=E'Colorful × Sexy',romanized_name=E'Karafuru × Sekushi' where id=157;
update songs set name=E'劣等上等',english_name=E'BRING IT ON',romanized_name=E'Rettou joutou' where id=158;
update songs set name=E'Star Story',english_name=E'Star Story',romanized_name=E'' where id=159;
update songs set name=E'パズル',english_name=E'Puzzle',romanized_name=E'Puzuru' where id=160;
update songs set name=E'キップル・インダストリー',english_name=E'Kipple Industry, Inc.',romanized_name=E'Kyupuru indasutorii' where id=161;
update songs set name=E'パラジクロロベンゼン',english_name=E'Continuing Dream',romanized_name=E'Yume no tsuzuki' where id=162;
update songs set name=E'MEGANE',english_name=E'Glasses',romanized_name=E'Megane' where id=163;
update songs set name=E'Change me',english_name=E'Change Me',romanized_name=E'' where id=164;
update songs set name=E'ドラマツルギー',english_name=E'Dramaturgy',romanized_name=E'Doramatsurugii' where id=165;
update songs set name=E'グリーンライツセレナーデ',english_name=E'Greenlights Serenade',romanized_name=E'Guriinraitsu Sereneede' where id=166;
update songs set name=E'マージナル',english_name=E'Marginal',romanized_name=E'Marginal' where id=167;
update songs set name=E'サウンド',english_name=E'sound',romanized_name=E'sound' where id=168;
update songs set name=E'ファインダー (DSLR remix - re:edit)',english_name=E'finder (DSLR remix - re:edit)',romanized_name=E'' where id=169;
update songs set name=E'Nyanyanyanyanyanyanya!',english_name=E'Nyanyanyanyanyanyanya!',romanized_name=E'' where id=170;
update songs set name=E'巴里映画少女',english_name=E'Paris Cinema Girl',romanized_name=E'Paris Eiga Shoujo' where id=171;
update songs set name=E'星屑ユートピア',english_name=E'Stardust Utopia',romanized_name=E'Hoshikuzu Utopia' where id=172;
update songs set name=E'Last Night, Good Night',english_name=E'Last Night, Good Night',romanized_name=E'' where id=173;
update songs set name=E'フキゲンワルツ',english_name=E'Bad Mood Waltz',romanized_name=E'Fukigen Waltz' where id=174;
update songs set name=E'Promise',english_name=E'Promise',romanized_name=E'' where id=175;
update songs set name=E'アドレサンス',english_name=E'Adolescence',romanized_name=E'Adolescence' where id=176;
update songs set name=E'Leia',english_name=E'Leia',romanized_name=E'' where id=177;
update songs set name=E'Stay with me',english_name=E'Stay with me',romanized_name=E'' where id=178;
update songs set name=E'Just Be Friends',english_name=E'Just Be Friends',romanized_name=E'' where id=21;
update songs set name=E'リモコン',english_name=E'Remote Controller',romanized_name=E'Rimokon' where id=51;