update songs set bpm=153 where id=1;
update songs set album_art='http://projectdivar.com/files/album_art/242.jpg' where id=  1; /*Catch the Wave                         */;
update songs set bpm=152 where id=2;
update songs set album_art='http://projectdivar.com/files/album_art/240.jpg' where id=  2; /*Alien Alien                            */;
update songs set bpm=130 where id=3;
update songs set album_art='http://projectdivar.com/files/album_art/243.jpg' where id=  3; /*39 Music!                              */;
update songs set bpm=128 where id=4;
update songs set album_art='http://projectdivar.com/files/album_art/247.jpg' where id=  4; /*Dreamin Chuchu                         */;
update songs set bpm=200 where id=5;
update songs set album_art='http://projectdivar.com/files/album_art/248.jpg' where id=  5; /*Hibana                                 */;
update songs set bpm=144 where id=6;
update songs set album_art='http://projectdivar.com/files/album_art/241.jpg' where id=  6; /*Ohedo Julia-Night                      */;
update songs set bpm=200 where id=7;
update songs set album_art='http://projectdivar.com/files/album_art/246.jpg' where id=  7; /*Teo                                    */;
update songs set bpm=264 where id=8;
update songs set album_art='http://projectdivar.com/files/album_art/245.jpg' where id=  8; /*Jitter Bug                             */;
update songs set bpm=172 where id=9;
update songs set album_art='http://projectdivar.com/files/album_art/244.jpg' where id=  9; /*Jigsaw Puzzle                          */;
update songs set bpm=150 where id=10;
update songs set album_art='http://projectdivar.com/files/album_art/249.jpg' where id= 10; /*Roki                                   */;
update songs set bpm=165 where id=11;
update songs set album_art='http://projectdivar.com/files/album_art/030.jpg' where id= 11; /*World is Mine                          */;
update songs set bpm=170 where id=12;
update songs set album_art='http://projectdivar.com/files/album_art/27.jpg' where id= 12; /*Melt                                   */;
update songs set bpm=215 where id=13;
update songs set album_art='http://projectdivar.com/files/album_art/025.jpg' where id= 13; /*Miracle Paint                          */;
update songs set bpm=76 where id=14;
update songs set album_art='http://projectdivar.com/files/album_art/196.jpg' where id= 14; /*Sakura no Ame                          */;
update songs set bpm=150 where id=15;
update songs set album_art='http://projectdivar.com/files/album_art/004.jpg' where id= 15; /*Electric Angel                         */;
update songs set bpm=240 where id=16;
update songs set album_art='http://projectdivar.com/files/album_art/016.jpg' where id= 16; /*Hatsune Miku no Shoushitsu -DEAD END-  */;
update songs set bpm=160 where id=17;
update songs set album_art='http://projectdivar.com/files/album_art/024.jpg' where id= 17; /*Miku Miku ni Shite Ageru♪              */;
update songs set bpm=170 where id=18;
update songs set album_art='http://projectdivar.com/files/album_art/059.jpg' where id= 18; /*Romeo to Cinderella                    */;
update songs set bpm=216 where id=19;
update songs set album_art='http://projectdivar.com/files/album_art/078.jpg' where id= 19; /*magnet                                 */;
update songs set bpm=136 where id=20;
update songs set album_art='http://projectdivar.com/files/album_art/060.jpg' where id= 20; /*Ai Kotoba                              */;
update songs set bpm=128 where id=21;
update songs set album_art='http://projectdivar.com/files/album_art/073.jpg' where id= 21; /*Just Be Friends                        */;
update songs set bpm=98 where id=22;
update songs set album_art='http://projectdivar.com/files/album_art/102.jpg' where id= 22; /*from Y to Y                            */;
update songs set bpm=150 where id=23;
update songs set album_art='http://projectdivar.com/files/album_art/062.jpg' where id= 23; /*PoPiPo                                 */;
update songs set bpm=144 where id=24;
update songs set album_art='http://projectdivar.com/files/album_art/056.jpg' where id= 24; /*Cantarella                             */;
update songs set bpm=90 where id=25;
update songs set album_art='http://projectdivar.com/files/album_art/087.jpg' where id= 25; /*Gemini                                 */;
update songs set bpm=100 where id=26;
update songs set album_art='http://projectdivar.com/files/album_art/075.jpg' where id= 26; /*Hajimete no Oto                        */;
update songs set bpm=146 where id=27;
update songs set album_art='http://projectdivar.com/files/album_art/074.jpg' where id= 27; /*Saihate                                */;
update songs set bpm=185 where id=28;
update songs set album_art='http://projectdivar.com/files/album_art/055.jpg' where id= 28; /*Colorful × Melody                      */;
update songs set bpm=200 where id=29;
update songs set album_art='http://projectdivar.com/files/album_art/097.jpg' where id= 29; /*Hatsune Miku no Gekishou               */;
update songs set bpm=180 where id=30;
update songs set album_art='http://projectdivar.com/files/album_art/114.jpg' where id= 30; /*Palette                                */;
update songs set bpm=162 where id=31;
update songs set album_art='http://projectdivar.com/files/album_art/122.jpg' where id= 31; /*SPiCa -39update songs set album_art='s Giving Day Edition-        */;
update songs set bpm=102 where id=32;
update songs set album_art='http://projectdivar.com/files/album_art/109.jpg' where id= 32; /*Tsugai Kogarashi                       */;
update songs set bpm=160 where id=33;
update songs set album_art='http://projectdivar.com/files/album_art/089.jpg' where id= 33; /*Luka Luka★Night Fever                  */;
update songs set bpm=150 where id=34;
update songs set album_art='http://projectdivar.com/files/album_art/120.jpg' where id= 34; /**Hello*/;
update songs set bpm=159 where id=35;
update songs set album_art='http://projectdivar.com/files/album_art/104.jpg' where id= 35; /*Ura-omote Lovers                       */;
update songs set bpm=195 where id=36;
update songs set album_art='http://projectdivar.com/files/album_art/123.jpg' where id= 36; /*Rolling Girl                           */;
update songs set bpm=110 where id=37;
update songs set album_art='http://projectdivar.com/files/album_art/157.jpg' where id= 37; /*Tricolor Airline                       */;
update songs set bpm=150 where id=38;
update songs set album_art='http://projectdivar.com/files/album_art/129.jpg' where id= 38; /*on the rocks                           */;
update songs set bpm=138 where id=39;
update songs set album_art='http://projectdivar.com/files/album_art/232.jpg' where id= 39; /*LOL -lots of laugh-                    */;
update songs set bpm=137 where id=40;
update songs set album_art='http://projectdivar.com/files/album_art/143.jpg' where id= 40; /*Shinkai Shoujo                         */;
update songs set bpm=220 where id=41;
update songs set album_art='http://projectdivar.com/files/album_art/231.jpg' where id= 41; /*Kimi no Taion                          */;
update songs set bpm=174 where id=42;
update songs set album_art='http://projectdivar.com/files/album_art/148.jpg' where id= 42; /*Cat Food                               */;
update songs set bpm=200 where id=43;
update songs set album_art='http://projectdivar.com/files/album_art/164.jpg' where id= 43; /*Himitsu Keisatsu                       */;
update songs set bpm=140 where id=44;
update songs set album_art='http://projectdivar.com/files/album_art/158.jpg' where id= 44; /*Melancholic                            */;
update songs set bpm=132 where id=45;
update songs set album_art='http://projectdivar.com/files/album_art/147.jpg' where id= 45; /*Weekender Girl                         */;
update songs set bpm=126 where id=46;
update songs set album_art='http://projectdivar.com/files/album_art/176.jpg' where id= 46; /*Time Machine                           */;
update songs set bpm=158 where id=47;
update songs set album_art='http://projectdivar.com/files/album_art/152.jpg' where id= 47; /*DYE                                    */;
update songs set bpm=175 where id=48;
update songs set album_art='http://projectdivar.com/files/album_art/149.jpg' where id= 48; /*Fire◎Flower                            */;
update songs set bpm=114 where id=49;
update songs set album_art='http://projectdivar.com/files/album_art/163.jpg' where id= 49; /*ACUTE                                  */;
update songs set bpm=135 where id=50;
update songs set album_art='http://projectdivar.com/files/album_art/202.jpg' where id= 50; /*Torinoko City                          */;
update songs set bpm=165 where id=51;
update songs set album_art='http://projectdivar.com/files/album_art/165.jpg' where id= 51; /*Rimokon                                */;
update songs set bpm=129 where id=52;
update songs set album_art='http://projectdivar.com/files/album_art/150.jpg' where id= 52; /*FREELY TOMORROW                        */;
update songs set bpm=130 where id=53;
update songs set album_art='http://projectdivar.com/files/album_art/162.jpg' where id= 53; /*Monochro∞Blue Sky                      */;
update songs set bpm=171 where id=54;
update songs set album_art='http://projectdivar.com/files/album_art/128.jpg' where id= 54; /*Worldupdate songs set album_art='s End Dancehall                  */;
update songs set bpm=175 where id=55;
update songs set album_art='http://projectdivar.com/files/album_art/175.jpg' where id= 55; /*Netoge Haijin Sprechchor               */;
update songs set bpm=140 where id=56;
update songs set album_art='http://projectdivar.com/files/album_art/184.jpg' where id= 56; /*Nostalogic                             */;
update songs set bpm=205 where id=57;
update songs set album_art='http://projectdivar.com/files/album_art/146.jpg' where id= 57; /*Unhappy Refrain                        */;
update songs set bpm=192 where id=58;
update songs set album_art='http://projectdivar.com/files/album_art/178.jpg' where id= 58; /*ODDS&ENDS                              */;
update songs set bpm=232 where id=59;
update songs set album_art='http://projectdivar.com/files/album_art/153.jpg' where id= 59; /*Tengaku                                */;
update songs set bpm=165 where id=60;
update songs set album_art='http://projectdivar.com/files/album_art/181.jpg' where id= 60; /*Black★Rock Shooter                     */;
update songs set bpm=165 where id=61;
update songs set album_art='http://projectdivar.com/files/album_art/204.jpg' where id= 61; /*Sadistic.Music∞Factory                 */;
update songs set bpm=150 where id=62;
update songs set album_art='http://projectdivar.com/files/album_art/154.jpg' where id= 62; /*Tell Your World                        */;
update songs set bpm=204 where id=63;
update songs set album_art='http://projectdivar.com/files/album_art/170.jpg' where id= 63; /*Tokyo Teddy Bear                       */;
update songs set bpm=132 where id=64;
update songs set album_art='http://projectdivar.com/files/album_art/180.jpg' where id= 64; /*Sweet Devil                            */;
update songs set bpm=154 where id=65;
update songs set album_art='http://projectdivar.com/files/album_art/198.jpg' where id= 65; /*Senbonzakura                           */;
update songs set bpm=123 where id=66;
update songs set album_art='http://projectdivar.com/files/album_art/207.jpg' where id= 66; /*Sweet Magic                            */;
update songs set bpm=170 where id=67;
update songs set album_art='http://projectdivar.com/files/album_art/201.jpg' where id= 67; /*Terekakushi Shishunki                  */;
update songs set bpm=190 where id=68;
update songs set album_art='http://projectdivar.com/files/album_art/236.jpg' where id= 68; /*Amatsukitsune                          */;
update songs set bpm=226 where id=69;
update songs set album_art='http://projectdivar.com/files/album_art/175.jpg' where id= 69; /*Ageage Again                           */;
update songs set bpm=125 where id=70;
update songs set album_art='http://projectdivar.com/files/album_art/177.jpg' where id= 70; /*1/6 -out of the gravity-               */;
update songs set bpm=145 where id=71;
update songs set album_art='http://projectdivar.com/files/album_art/237.jpg' where id= 71; /*1925                                   */;
update songs set bpm=147 where id=72;
update songs set album_art='http://projectdivar.com/files/album_art/228.jpg' where id= 72; /*Cendrillon                             */;
update songs set bpm=127 where id=73;
update songs set album_art='http://projectdivar.com/files/album_art/193.jpg' where id= 73; /*Snowman                                */;
update songs set bpm=130 where id=74;
update songs set album_art='http://projectdivar.com/files/album_art/230.jpg' where id= 74; /*Gaikotsu Gakudan to Lilia              */;
update songs set bpm=150 where id=75;
update songs set album_art='http://projectdivar.com/files/album_art/212.jpg' where id= 75; /*Arifureta Sekai Seifuku                */;
update songs set bpm=125 where id=76;
update songs set album_art='http://projectdivar.com/files/album_art/179.jpg' where id= 76; /*Interviewer                            */;
update songs set bpm=135 where id=77;
update songs set album_art='http://projectdivar.com/files/album_art/234.jpg' where id= 77; /*Piano × Forte × Scandal                */;
update songs set bpm=130 where id=78;
update songs set album_art='http://projectdivar.com/files/album_art/229.jpg' where id= 78; /*shake it!                              */;
update songs set bpm=125 where id=79;
update songs set album_art='http://projectdivar.com/files/album_art/209.jpg' where id= 79; /*Akatsuki Arrival                       */;
update songs set bpm=140 where id=80;
update songs set album_art='http://projectdivar.com/files/album_art/213.jpg' where id= 80; /*Glory 3usi9                            */;
update songs set bpm=120 where id=81;
update songs set album_art='http://projectdivar.com/files/album_art/208.jpg' where id= 81; /*Suki Kirai                             */;
update songs set bpm=195 where id=82;
update songs set album_art='http://projectdivar.com/files/album_art/220.jpg' where id= 82; /*Yubikiri                               */;
update songs set bpm=228 where id=83;
update songs set album_art='http://projectdivar.com/files/album_art/225.jpg' where id= 83; /*Blackjack                              */;
update songs set bpm=102 where id=84;
update songs set album_art='http://projectdivar.com/files/album_art/218.jpg' where id= 84; /*Karakuri Pierrot                       */;
update songs set bpm=178 where id=85;
update songs set album_art='http://projectdivar.com/files/album_art/224.jpg' where id= 85; /*Narisumashi Genga                      */;
update songs set bpm=128 where id=86;
update songs set album_art='http://projectdivar.com/files/album_art/215.jpg' where id= 86; /*e*/;
update songs set bpm=168 where id=87;
update songs set album_art='http://projectdivar.com/files/album_art/190.jpg' where id= 87; /*Hello*/;
update songs set bpm=140 where id=88;
update songs set album_art='http://projectdivar.com/files/album_art/211.jpg' where id= 88; /*Meteor                                 */;
update songs set bpm=82 where id=89;
update songs set album_art='http://projectdivar.com/files/album_art/221.jpg' where id= 89; /*soundless voice                        */;
update songs set bpm=138 where id=90;
update songs set album_art='http://projectdivar.com/files/album_art/223.jpg' where id= 90; /*erase or zero                          */;
update songs set bpm=160 where id=91;
update songs set album_art='http://projectdivar.com/files/album_art/206.jpg' where id= 91; /*Envy Cat Walk                          */;
update songs set bpm=143 where id=92;
update songs set album_art='http://projectdivar.com/files/album_art/214.jpg' where id= 92; /*DECORATOR                              */;
update songs set bpm=180 where id=93;
update songs set album_art='http://projectdivar.com/files/album_art/210.jpg' where id= 93; /*Nijigen Dream Fever                    */;
update songs set bpm=175 where id=94;
update songs set album_art='http://projectdivar.com/files/album_art/205.jpg' where id= 94; /*Hajimemashite Chikyuujin-san           */;
update songs set bpm=128 where id=95;
update songs set album_art='http://projectdivar.com/files/album_art/233.jpg' where id= 95; /*Hand in Hand                           */;
update songs set bpm=200 where id=96;
update songs set album_art='http://projectdivar.com/files/album_art/131.jpg' where id= 96; /*Shiroi Yuki no Princess wa             */;
update songs set bpm=175 where id=97;
update songs set album_art='http://projectdivar.com/files/album_art/033.jpg' where id= 97; /*39                                     */;
update songs set bpm=250 where id=98;
update songs set album_art='http://projectdivar.com/files/album_art/137.jpg' where id= 98; /*Black Gold                             */;
update songs set bpm=140 where id=99;
update songs set album_art='http://projectdivar.com/files/album_art/235.jpg' where id= 99; /*Hibikase                               */;
update songs set bpm=210 where id=100;
update songs set album_art='http://projectdivar.com/files/album_art/238.jpg' where id=100; /*Ghost Rule                             */;
update songs set bpm=96 where id=101;
update songs set album_art='http://projectdivar.com/files/album_art/239.jpg' where id=101; /*Suna no Wakusei                        */;
update songs set bpm=133 where id=102;
update songs set album_art='http://projectdivar.com/files/album_art/009.jpg' where id=102; /*The secret garden                      */;
update songs set bpm=185 where id=103;
update songs set album_art='http://projectdivar.com/files/album_art/057.jpg' where id=103; /*Kocchi Muite Baby                      */;
update songs set bpm=138 where id=104;
update songs set album_art='http://projectdivar.com/files/album_art/111.jpg' where id=104; /*Sekiranun Graffiti                     */;
update songs set bpm=160 where id=105;
update songs set album_art='http://projectdivar.com/files/album_art/132.jpg' where id=105; /*YUMEYUME                               */;
update songs set bpm=169 where id=106;
update songs set album_art='http://projectdivar.com/files/album_art/110.jpg' where id=106; /*Musunde Hiraite Rasetsu to Mukuro      */;
update songs set bpm=141 where id=107;
update songs set album_art='http://projectdivar.com/files/album_art/194.jpg' where id=107; /*electro saturator                      */;
update songs set bpm=165 where id=108;
update songs set album_art='http://projectdivar.com/files/album_art/064.jpg' where id=108; /*Roshin Yuukai                          */;
update songs set bpm=138 where id=109;
update songs set album_art='http://projectdivar.com/files/album_art/096.jpg' where id=109; /*Double Lariat                          */;
update songs set bpm=130 where id=110;
update songs set album_art='http://projectdivar.com/files/album_art/155.jpg' where id=110; /*Hai wa Hai ni                          */;
update songs set bpm=116 where id=111;
update songs set album_art='http://projectdivar.com/files/album_art/219.jpg' where id=111; /*Kowase Kowase                          */;
update songs set bpm=180 where id=112;
update songs set album_art='http://projectdivar.com/files/album_art/076.jpg' where id=112; /*Hajimete no Koi ga Owaru Toki          */;
update songs set bpm=174 where id=113;
update songs set album_art='http://projectdivar.com/files/album_art/127.jpg' where id=113; /*Mousou Sketch                          */;
update songs set bpm=220 where id=114;
update songs set album_art='http://projectdivar.com/files/album_art/169.jpg' where id=114; /*Den Paradigm                           */;
update songs set bpm=180 where id=115;
update songs set album_art='http://projectdivar.com/files/album_art/124.jpg' where id=115; /*Kodoku no Hate                         */;
update songs set bpm=140 where id=116;
update songs set album_art='http://projectdivar.com/files/album_art/063.jpg' where id=116; /*Migikata no Chou                       */;
update songs set bpm=120 where id=117;
update songs set album_art='http://projectdivar.com/files/album_art/125.jpg' where id=117; /*No Logic                               */;
update songs set bpm=192 where id=118;
update songs set album_art='http://projectdivar.com/files/album_art/200.jpg' where id=118; /*E? Aa*/;
update songs set bpm=125 where id=119;
update songs set album_art='http://projectdivar.com/files/album_art/015.jpg' where id=119; /*packaged                               */;
update songs set bpm=135 where id=120;
update songs set album_art='http://projectdivar.com/files/album_art/085.jpg' where id=120; /*Kyodai Shoujo                          */;
update songs set bpm=180 where id=121;
update songs set album_art='http://projectdivar.com/files/album_art/174.jpg' where id=121; /*Summer Idol                            */;
update songs set bpm=108 where id=122;
update songs set album_art='http://projectdivar.com/files/album_art/112.jpg' where id=122; /*Sennen no Dokusou Ka                   */;
update songs set bpm=180 where id=123;
update songs set album_art='http://projectdivar.com/files/album_art/116.jpg' where id=123; /*Boukyaku Shinjuu                       */;
update songs set bpm=180 where id=124;
update songs set album_art='http://projectdivar.com/files/album_art/199.jpg' where id=124; /*WORLDupdate songs set album_art='S END UMBRELLA                   */;
update songs set bpm=130 where id=125;
update songs set album_art='http://projectdivar.com/files/album_art/005.jpg' where id=125; /*Koisuru VOC@LOID                       */;
update songs set bpm=163 where id=126;
update songs set album_art='http://projectdivar.com/files/album_art/203.jpg' where id=126; /*Kami Kyoku                             */;
update songs set bpm=127 where id=127;
update songs set album_art='http://projectdivar.com/files/album_art/084.jpg' where id=127; /*Yellow                                 */;
update songs set bpm=220 where id=128;
update songs set album_art='http://projectdivar.com/files/album_art/160.jpg' where id=128; /*Negaposi*Continues                     */;
update songs set bpm=190 where id=129;
update songs set album_art='http://projectdivar.com/files/album_art/159.jpg' where id=129; /*SING&SMILE                             */;
update songs set bpm=98 where id=130;
update songs set album_art='http://projectdivar.com/files/album_art/118.jpg' where id=130; /*Uta ni Katachi wa Nai Keredo           */;
update songs set bpm=135 where id=131;
update songs set album_art='http://projectdivar.com/files/album_art/100.jpg' where id=131; /*Dear                                   */;
update songs set bpm=175 where id=132;
update songs set album_art='http://projectdivar.com/files/album_art/167.jpg' where id=132; /*Dou Iu Koto na no!?                    */;
update songs set bpm=150 where id=133;
update songs set album_art='http://projectdivar.com/files/album_art/095.jpg' where id=133; /*Clover♣Club                            */;
update songs set bpm=200 where id=134;
update songs set album_art='http://projectdivar.com/files/album_art/189.jpg' where id=134; /*Rin-chan Nau!                          */;
update songs set bpm=170 where id=135;
update songs set album_art='http://projectdivar.com/files/album_art/139.jpg' where id=135; /*Shinkai City Underground               */;
update songs set bpm=180 where id=136;
update songs set album_art='http://projectdivar.com/files/album_art/216.jpg' where id=136; /*Nisoku Hokou                           */;
update songs set bpm=130 where id=137;
update songs set album_art='http://projectdivar.com/files/album_art/217.jpg' where id=137; /*PIANO*GIRL                             */;
update songs set bpm=136 where id=138;
update songs set album_art='http://projectdivar.com/files/album_art/156.jpg' where id=138; /*Systematic Love                        */;
update songs set bpm=140 where id=139;
update songs set album_art='http://projectdivar.com/files/album_art/072.jpg' where id=139; /*Kokoro                                 */;
update songs set bpm=197 where id=140;
update songs set album_art='http://projectdivar.com/files/album_art/188.jpg' where id=140; /*Yumekui Shirokuro Baku                 */;
update songs set bpm=110 where id=141;
update songs set album_art='http://projectdivar.com/files/album_art/222.jpg' where id=141; /*Knife                                  */;
update songs set bpm=152 where id=142;
update songs set album_art='http://projectdivar.com/files/album_art/250.jpg' where id=142; /*Bless Your Breath                      */;
update songs set bpm=175 where id=143;
update songs set album_art='http://projectdivar.com/files/album_art/006.jpg' where id=143; /*Koi wa Sensou                          */;
update songs set bpm=89 where id=144;
update songs set album_art='http://projectdivar.com/files/album_art/000.jpg' where id=144; /*Anata no Utahime                       */;
update songs set bpm=82 where id=145;
update songs set album_art='http://projectdivar.com/files/album_art/121.jpg' where id=145; /*Starduster                             */;
update songs set bpm=195 where id=146;
update songs set album_art='http://projectdivar.com/files/album_art/035.jpg' where id=146; /*StargazeR                              */;
update songs set bpm=124 where id=147;
update songs set album_art='http://projectdivar.com/files/album_art/117.jpg' where id=147; /*Rin Rin Signal                         */;
update songs set bpm=148 where id=148;
update songs set album_art='http://projectdivar.com/files/album_art/141.jpg' where id=148; /*Rosary Pale                            */;
update songs set bpm=150 where id=149;
update songs set album_art='http://projectdivar.com/files/album_art/051.jpg' where id=149; /*Tajuu Mirai no Quartet ~QUARTET THEME~ */;
update songs set bpm=182 where id=150;
update songs set album_art='http://projectdivar.com/files/album_art/138.jpg' where id=150; /*LIKE THE WIND                          */;
update songs set bpm=172 where id=151;
update songs set album_art='http://projectdivar.com/files/album_art/134.jpg' where id=151; /*AFTER BURNER                           */;