var songs = [['Catch the Wave','Catch the Wave','kz','Miku'],
['エイリアンエイリアン (Alien Alien)','Alien Alien','NayutalieN','Miku'],
['39みゅーじっく！ (39 Music!)','39 Music!','Mikito-P','Miku'],
['どりーみんチュチュ (Dreamin Chuchu)','Dreamin Chuchu','emon(Tes.)','Luka'],
['ヒバナ (Hibana)','HIBANA','DECO*27','Miku'],
['大江戸ジュリアナイト (Ohedo Julia-Night)','Ohedo Julia-Night','Mitchie M','Miku, KAITO'],
['テオ (Teo)','Teo','Omoi','Miku'],
['ジターバグ (Jitter Bug)','Jitter Bug','Hachiya Nanashi','MEIKO, Miku'],
['ジグソーパズル (Jigsaw Puzzle)','Jigsaw Puzzle','Mafumafu','Len'],
['ロキ (Roki)','ROKI','Mikito-P','Rin, Len'],
['ワールドイズマイン (World is Mine)','World is Mine','ryo','Miku'],
['メルト (Melt)','Melt','ryo','Miku'],
['ミラクルペイント (Miracle Paint)','Miracle Paint','OSTER project','Miku'],
['桜ノ雨 (Sakura no Ame)','Rain of Cherry Blossoms','halyosy','Miku'],
['えれくとりっく・えんじぇぅ (Electric Angel)','Electric Angel','Yasuo-P','Miku'],
['初音ミクの消失 -DEAD END- (Hatsune Miku no Shoushitsu -DEAD END-)','The Disappearance of Hatsune Miku -DEAD END-','cosMo','Miku'],
['みくみくにしてあげる♪ (Miku Miku ni Shite Ageru♪)','I\'ll Miku-Miku You♪ (For Reals)','ika','Miku'],
['ロミオとシンデレラ (Romeo to Cinderella)','Romeo and Cinderella','doriko','Miku'],
['magnet','magnet','minato','Miku, Luka'],
['愛言葉 (Ai Kotoba)','Love Words','DECO*27','Miku'],
['Just Be Friends','Just Be Friends','Dixie Flatline','Luka'],
['from Y to Y','from Y to Y','JimmyThumb-P','Miku'],
['ぽっぴっぽー (PoPiPo)','PoPiPo (Vegetable Juice)','LamazeP','Miku'],
['カンタレラ (Cantarella)','Cantarella','Kurousa-P','KAITO, Miku'],
['ジェミニ (Gemini)','Gemini','Dixie Flatline','Rin, Len'],
['ハジメテノオト (Hajimete no Oto)','The First Sound','malo','Miku'],
['サイハテ (Saihate)','The Farthest Ends','Kobayashi Onyx','Miku'],
['カラフル×メロディ (Colorful × Melody)','Colorful × Melody','Team MOER','Miku, Rin'],
['初音ミクの激唱 (Hatsune Miku no Gekishou)','The Intense Voice of Hatsune Miku','cosMo','Miku'],
['Palette','Palette','Yuyoyuppe, meola','Luka'],
['SPiCa -39\'s Giving Day Edition-','SPiCa -39\'s Giving Day Edition-','Toku-P, kentax','Miku'],
['番凩 (Tsugai Kogarashi)','Wintry Winds','sigotositeP','MEIKO, KAITO'],
['ルカルカ★ナイトフィーバー (Luka Luka★Night Fever)','Luka Luka★Night Fever','samfree','Luka'],
['＊ハロー、プラネット。 (*Hello, Planet.) (I.M.PLSE-EDIT)','*Hello, Planet. (I.M.PLSE-EDIT)','sasakure.UK','Miku'],
['裏表ラバーズ (Ura-omote Lovers)','Two-Sided Lovers','wowaka','Miku'],
['ローリンガール (Rolling Girl)','Rolling Girl','wowaka','Miku'],
['トリコロール・エア・ライン (Tricolor Airline)','Tricolore Airline','Atsuzou-kun','Miku'],
['on the rocks','on the rocks','OSTER project','MEIKO, KAITO'],
['LOL -lots of laugh-','LOL -lots of laugh-','mikumix','Miku'],
['深海少女 (Shinkai Shoujo)','Deep Sea Girl','Yuuyu-P','Miku'],
['君の体温 (Kimi no Taion)','Your Body Temperature','Kuwagata-P','Miku'],
['キャットフード (Cat Food)','Cat Food','doriko','Miku'],
['秘密警察 (Himitsu Keisatsu)','Secret Police','Buriru-P','Miku'],
['メランコリック (Melancholic)','Melancholic','Junky','Rin'],
['Weekender Girl','Weekender Girl','kz, Hachioji-P','Miku'],
['タイムマシン (Time Machine)','Time Machine','1640mP','Miku'],
['DYE','DYE','AVTechNO!','Luka'],
['Fire◎Flower','Fire◎Flower','halyosy','Len'],
['ACUTE','ACUTE','Kurousa-P','KAITO, Miku, Luka'],
['トリノコシティ (Torinoko City)','Left-Behind City','40mP','Miku'],
['リモコン (Rimokon)','Remote Controller','Jesus-P','Rin, Len'],
['FREELY TOMORROW','FREELY TOMORROW','Mitchie M','Miku'],
['モノクロ∞ブルースカイ (Monochro∞Blue Sky)','Monochrome ∞ Blue Sky','Noboru↑-P','Miku'],
['ワールズエンド・ダンスホール (World\'s End Dancehall)','World\'s End Dancehall','wowaka','Miku, Luka'],
['ネトゲ廃人シュプレヒコール (Netoge Haijin Sprechchor)','The MMORPG Addict\'s Anthem','TENKOMORI','Miku'],
['Nostalogic','Nostalogic','yuukiss, rose','MEIKO'],
['アンハッピーリフレイン (Unhappy Refrain)','Unhappy Refrain','wowaka','Miku'],
['ODDS&ENDS','ODDS&ENDS','ryo','Miku'],
['天樂 (Tengaku)','Music of Heavens','Yuuyu-P','Rin'],
['ブラック★ロックシューター (Black★Rock Shooter)','Black★Rock Shooter','ryo','Miku'],
['Sadistic.Music∞Factory','Sadistic.Music∞Factory','cosMo','Miku'],
['Tell Your World','Tell Your World','kz','Miku'],
['東京テディベア (Tokyo Teddy Bear)','Tokyo Teddy Bear','Neru','Rin'],
['Sweet Devil','Sweet Devil','Hachioji-P, q*Left','Miku'],
['千本桜 (Senbonzakura)','A Thousand Cherry Blossoms','Kurousa-P','Miku'],
['スイートマジック (Sweet Magic)','Sweet Magic','Junky','Rin'],
['テレカクシ思春期 (Terekakushi Shishunki)','Embarrassment-Hiding Adolescence','HoneyWorks','Len'],
['アマツキツネ (Amatsukitsune)','The Celestial Fox','marasy','Rin'],
['アゲアゲアゲイン (Ageage Again)','Ageage Again','Mitchie M','Miku'],
['1/6 -out of the gravity-','1/6 -out of the gravity-','Vocaliod-P','Miku'],
['1925','1925','T-POCKET','Miku'],
['サンドリヨン (Cendrillon)','Cendrillon','Signal-P, orange','Miku, KAITO'],
['スノーマン (Snowman)','Snowman','halyosy','KAITO'],
['骸骨楽団とリリア (Gaikotsu Gakudan to Lilia)','Skeleton Orchestra and Lilia','Tohma','Miku'],
['ありふれたせかいせいふく (Arifureta Sekai Seifuku)','Common World Domination','Pinocchio-P','Miku'],
['インタビュア (Interviewer)','Interviewer','Kuwagata-P','Luka'],
['ピアノ×フォルテ×スキャンダル (Piano × Forte × Scandal)','Piano × Forte × Scandal','OSTER project','MEIKO'],
['shake it!','shake it!','emon(Tes.)','Miku, Rin, Len'],
['アカツキアライヴァル (Akatsuki Arrival)','Daybreak Arrival','Last Note.','Miku, Luka'],
['Glory 3usi9','Glory 3usi9','Hoehoe-P','Miku'],
['スキキライ (Suki Kirai)','Love-Hate','HoneyWorks','Rin, Len'],
['指切り (Yubikiri)','Pinky Swear','Scop','Miku'],
['Blackjack','Blackjack','Yucha-P','Luka'],
['からくりピエロ (Karakuri Pierrot)','Clockwork Clown','40mP','Miku'],
['なりすましゲンガー (Narisumashi Genga)','Doubleganger','KulfiQ','Rin, Miku'],
['こちら、幸福安心委員会です。 (Kochira, Koufuku Anshin Iinkai desu.)','This is the Happiness and Peace of Mind Committee','Utata-P, Tory Hitsuji','Miku'],
['Hello, Worker','Hello, Worker','Hayashikei','Luka'],
['メテオ (Meteor)','Meteor','John','Miku'],
['soundless voice','soundless voice','Hitoshizuku-P','Len'],
['erase or zero','erase or zero','Crystal-P','Len, KAITO'],
['エンヴィキャットウォーク (Envy Cat Walk)','Envy Cat Walk','Tohma','Miku'],
['DECORATOR','DECORATOR','kz','Miku'],
['二次元ドリームフィーバー (Nijigen Dream Fever)','2D Dream Fever','PolyphonicBranch','Miku'],
['はじめまして地球人さん (Hajimemashite Chikyuujin-san)','Nice to Meet You, Mr. Earthling','Pinocchio-P','Miku'],
['Hand in Hand','Hand in Hand','kz','Miku'],
['白い雪のプリンセスは (Shiroi Yuki no Princess wa)','The Snow White Princess is','Noboru↑-P','Miku'],
['39','39','DECO*27, sasakure.UK','Miku'],
['ブラックゴールド (Black Gold)','Black Gold','otetsu','Luka'],
['ヒビカセ (Hibikase)','Resonate','Giga-P, Reol','Miku'],
['ゴーストルール (Ghost Rule)','Ghost Rule','DECO*27','Miku'],
['砂の惑星 (Suna no Wakusei)','DUNE','Hachi','Miku'],
['The secret garden','The secret garden','Satoru Kosaki, Aki Hata','Miku'],
['こっち向いて Baby (Kocchi Muite Baby)','Look This Way, Baby','ryo','Miku'],
['積乱雲グラフィティ (Sekiranun Graffiti)','Cumulonimbus Cloud Graffiti','ryo, Dixie Flatline','Miku'],
['ゆめゆめ (YUMEYUME)','DREAM DREAM','DECO*27','Miku'],
['結ンデ開イテ羅刹ト骸 (Musunde Hiraite Rasetsu to Mukuro)','Close and Open, Demons and The Dead','Hachi','Miku'],
['エレクトロサチュレイタ (electro saturator)','electro saturator','tilt-six','Miku'],
['炉心融解 (Roshin Yuukai)','Meltdown','iroha(sasaki), kuma(alfred)','Rin'],
['ダブルラリアット (Double Lariat)','Double Lariat','Agoaniki-P','Luka'],
['ハイハハイニ (Hai wa Hai ni)','Ashes to Ashes','Tennen, niboshi','KAITO'],
['壊セ壊セ (Kowase Kowase)','Break It, Break It!','E.L.V.N','MEIKO'],
['初めての恋が終わる時 (Hajimete no Koi ga Owaru Toki)','When First Love Ends','ryo','Miku'],
['妄想スケッチ (Mousou Sketch)','Delusion Sketch','40mP','Miku'],
['デンパラダイム (Den Paradigm)','Den Paradigm','lumo','Miku'],
['孤独の果て (Kodoku no Hate) -extend edition-','Solitude\'s End -extend edition-','Hikarisyuyo','Rin, Len'],
['右肩の蝶 (Migikata no Chou)','Butterfly on Your Right Shoulder','Nori-P, Yura Mizuno','Len'],
['No Logic','No Logic','JimmyThumb-P','Luka'],
['え？あぁ、そう。 (E? Aa, Sou.)','Hm? Ah, Yes.','Chouchou-P','Miku'],
['packaged','packaged','kz','Miku'],
['巨大少女 (Kyodai Shoujo)','Gigantic Girl','40mP','Miku'],
['サマーアイドル (Summer Idol)','Summer Idol','OSTER project','Miku, Rin'],
['千年の独奏歌 (Sennen no Dokusou Ka)','Thousand Year Solo','yanagi-P','KAITO'],
['忘却心中 (Boukyaku Shinjuu)','Lover\'s Suicide Oblivion','OPA, Asaki No\'9','MEIKO'],
['WORLD\'S END UMBRELLA','WORLD\'S END UMBRELLA','Hachi','Miku'],
['恋スルVOC@LOID (Koisuru VOC@LOID)','VOC@LOID in Love','OSTER project','Miku'],
['神曲 (Kami Kyoku)','God-Tier Tune','Onew-P','Miku'],
['Yellow','Yellow','kz','Miku'],
['ネガポジ＊コンティニューズ (Negaposi*Continues)','Negaposi*Continues','sasakure.UK','Miku'],
['SING&SMILE','SING&SMILE','Re:nG','Miku'],
['歌に形はないけれど (Uta ni Katachi wa Nai Keredo)','Though My Song Has No Form','doriko','Miku'],
['Dear','Dear','19\'s Sound Factory','Miku'],
['どういうことなの！？ (Dou Iu Koto na no!?)','What Do You Mean!?','Kuchibashi-P','Miku'],
['クローバー♣クラブ (Clover♣Club)','Clover♣Club','Yuuyu-P','Miku'],
['リンちゃんなう！ (Rin-chan Nau!)','Rin-chan Now!','Owata-P, sezu','Miku, Luka'],
['深海シティアンダーグラウンド (Shinkai City Underground)','Deep Sea City Underground','Tanaka-B','Rin'],
['二息歩行 (Nisoku Hokou)','Two Breaths Walking','DECO*27','Miku'],
['PIANO*GIRL','PIANO*GIRL','OSTER project','Miku'],
['システマティック・ラヴ (Systematic Love)','Systematic Love','Camellia, TENKOMORI','Miku'],
['ココロ (Kokoro)','Heart','Toraboruta-P','Rin'],
['夢喰い白黒バク (Yumekui Shirokuro Baku)','Dream-Eating Monochrome Baku','Nem','Len'],
['Knife','Knife','rerulili, mal','Rin, Miku, Len']]


function getSQLString(songs) {
	var finalString = "";
	for (var i=0;i<songs.length;i++) {
		finalString += "insert into songs(name,romanized_name,english_name,artist,vocaloid) values ("
		for (var j=0;j<songs[i].length;j++) {
			var item = songs[i][j].replace('\'','\\\'')
			switch (j) {
				case 0:{
					if (item.includes("(")) {
						var song = item.slice(0,item.indexOf(' ('))+item.slice(item.indexOf(')')+1);
						var romanized = item.slice(item.indexOf('(')+1,item.indexOf(')'));
						
						finalString+="E'"+song+"',E'"+romanized+"'"
					} else {
						finalString+="E'"+item+"',E''"
					}
				}break;
				default:{
					finalString+=",E'"+item+"'"
				}
			}
		}
		finalString+=");\n"
	}
	return finalString;
}

console.log(getSQLString(songs));