insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'Catch the Wave',E'',E'Catch the Wave',E'kz',E'Miku');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'エイリアンエイリアン',E'Alien Alien',E'Alien Alien',E'NayutalieN',E'Miku');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'39みゅーじっく！',E'39 Music!',E'39 Music!',E'Mikito-P',E'Miku');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'どりーみんチュチュ',E'Dreamin Chuchu',E'Dreamin Chuchu',E'emon(Tes.)',E'Luka');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'ヒバナ',E'Hibana',E'HIBANA',E'DECO*27',E'Miku');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'大江戸ジュリアナイト',E'Ohedo Julia-Night',E'Ohedo Julia-Night',E'Mitchie M',E'Miku, KAITO');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'テオ',E'Teo',E'Teo',E'Omoi',E'Miku');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'ジターバグ',E'Jitter Bug',E'Jitter Bug',E'Hachiya Nanashi',E'MEIKO, Miku');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'ジグソーパズル',E'Jigsaw Puzzle',E'Jigsaw Puzzle',E'Mafumafu',E'Len');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'ロキ',E'Roki',E'ROKI',E'Mikito-P',E'Rin, Len');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'ワールドイズマイン',E'World is Mine',E'World is Mine',E'ryo',E'Miku');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'メルト',E'Melt',E'Melt',E'ryo',E'Miku');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'ミラクルペイント',E'Miracle Paint',E'Miracle Paint',E'OSTER project',E'Miku');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'桜ノ雨',E'Sakura no Ame',E'Rain of Cherry Blossoms',E'halyosy',E'Miku');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'えれくとりっく・えんじぇぅ',E'Electric Angel',E'Electric Angel',E'Yasuo-P',E'Miku');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'初音ミクの消失 -DEAD END-',E'Hatsune Miku no Shoushitsu -DEAD END-',E'The Disappearance of Hatsune Miku -DEAD END-',E'cosMo',E'Miku');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'みくみくにしてあげる♪',E'Miku Miku ni Shite Ageru♪',E'I\'ll Miku-Miku You♪ (For Reals)',E'ika',E'Miku');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'ロミオとシンデレラ',E'Romeo to Cinderella',E'Romeo and Cinderella',E'doriko',E'Miku');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'magnet',E'',E'magnet',E'minato',E'Miku, Luka');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'愛言葉',E'Ai Kotoba',E'Love Words',E'DECO*27',E'Miku');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'Just Be Friends',E'',E'Just Be Friends',E'Dixie Flatline',E'Luka');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'from Y to Y',E'',E'from Y to Y',E'JimmyThumb-P',E'Miku');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'ぽっぴっぽー',E'PoPiPo',E'PoPiPo (Vegetable Juice)',E'LamazeP',E'Miku');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'カンタレラ',E'Cantarella',E'Cantarella',E'Kurousa-P',E'KAITO, Miku');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'ジェミニ',E'Gemini',E'Gemini',E'Dixie Flatline',E'Rin, Len');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'ハジメテノオト',E'Hajimete no Oto',E'The First Sound',E'malo',E'Miku');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'サイハテ',E'Saihate',E'The Farthest Ends',E'Kobayashi Onyx',E'Miku');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'カラフル×メロディ',E'Colorful × Melody',E'Colorful × Melody',E'Team MOER',E'Miku, Rin');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'初音ミクの激唱',E'Hatsune Miku no Gekishou',E'The Intense Voice of Hatsune Miku',E'cosMo',E'Miku');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'Palette',E'',E'Palette',E'Yuyoyuppe, meola',E'Luka');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'SPiCa -39\'s Giving Day Edition-',E'',E'SPiCa -39\'s Giving Day Edition-',E'Toku-P, kentax',E'Miku');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'番凩',E'Tsugai Kogarashi',E'Wintry Winds',E'sigotositeP',E'MEIKO, KAITO');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'ルカルカ★ナイトフィーバー',E'Luka Luka★Night Fever',E'Luka Luka★Night Fever',E'samfree',E'Luka');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'＊ハロー、プラネット。 (I.M.PLSE-EDIT)',E'*Hello, Planet.',E'*Hello, Planet. (I.M.PLSE-EDIT)',E'sasakure.UK',E'Miku');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'裏表ラバーズ',E'Ura-omote Lovers',E'Two-Sided Lovers',E'wowaka',E'Miku');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'ローリンガール',E'Rolling Girl',E'Rolling Girl',E'wowaka',E'Miku');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'トリコロール・エア・ライン',E'Tricolor Airline',E'Tricolore Airline',E'Atsuzou-kun',E'Miku');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'on the rocks',E'',E'on the rocks',E'OSTER project',E'MEIKO, KAITO');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'LOL -lots of laugh-',E'',E'LOL -lots of laugh-',E'mikumix',E'Miku');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'深海少女',E'Shinkai Shoujo',E'Deep Sea Girl',E'Yuuyu-P',E'Miku');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'君の体温',E'Kimi no Taion',E'Your Body Temperature',E'Kuwagata-P',E'Miku');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'キャットフード',E'Cat Food',E'Cat Food',E'doriko',E'Miku');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'秘密警察',E'Himitsu Keisatsu',E'Secret Police',E'Buriru-P',E'Miku');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'メランコリック',E'Melancholic',E'Melancholic',E'Junky',E'Rin');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'Weekender Girl',E'',E'Weekender Girl',E'kz, Hachioji-P',E'Miku');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'タイムマシン',E'Time Machine',E'Time Machine',E'1640mP',E'Miku');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'DYE',E'',E'DYE',E'AVTechNO!',E'Luka');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'Fire◎Flower',E'',E'Fire◎Flower',E'halyosy',E'Len');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'ACUTE',E'',E'ACUTE',E'Kurousa-P',E'KAITO, Miku, Luka');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'トリノコシティ',E'Torinoko City',E'Left-Behind City',E'40mP',E'Miku');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'リモコン',E'Rimokon',E'Remote Controller',E'Jesus-P',E'Rin, Len');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'FREELY TOMORROW',E'',E'FREELY TOMORROW',E'Mitchie M',E'Miku');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'モノクロ∞ブルースカイ',E'Monochro∞Blue Sky',E'Monochrome ∞ Blue Sky',E'Noboru↑-P',E'Miku');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'ワールズエンド・ダンスホール',E'World\'s End Dancehall',E'World\'s End Dancehall',E'wowaka',E'Miku, Luka');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'ネトゲ廃人シュプレヒコール',E'Netoge Haijin Sprechchor',E'The MMORPG Addict\'s Anthem',E'TENKOMORI',E'Miku');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'Nostalogic',E'',E'Nostalogic',E'yuukiss, rose',E'MEIKO');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'アンハッピーリフレイン',E'Unhappy Refrain',E'Unhappy Refrain',E'wowaka',E'Miku');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'ODDS&ENDS',E'',E'ODDS&ENDS',E'ryo',E'Miku');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'天樂',E'Tengaku',E'Music of Heavens',E'Yuuyu-P',E'Rin');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'ブラック★ロックシューター',E'Black★Rock Shooter',E'Black★Rock Shooter',E'ryo',E'Miku');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'Sadistic.Music∞Factory',E'',E'Sadistic.Music∞Factory',E'cosMo',E'Miku');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'Tell Your World',E'',E'Tell Your World',E'kz',E'Miku');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'東京テディベア',E'Tokyo Teddy Bear',E'Tokyo Teddy Bear',E'Neru',E'Rin');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'Sweet Devil',E'',E'Sweet Devil',E'Hachioji-P, q*Left',E'Miku');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'千本桜',E'Senbonzakura',E'A Thousand Cherry Blossoms',E'Kurousa-P',E'Miku');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'スイートマジック',E'Sweet Magic',E'Sweet Magic',E'Junky',E'Rin');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'テレカクシ思春期',E'Terekakushi Shishunki',E'Embarrassment-Hiding Adolescence',E'HoneyWorks',E'Len');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'アマツキツネ',E'Amatsukitsune',E'The Celestial Fox',E'marasy',E'Rin');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'アゲアゲアゲイン',E'Ageage Again',E'Ageage Again',E'Mitchie M',E'Miku');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'1/6 -out of the gravity-',E'',E'1/6 -out of the gravity-',E'Vocaliod-P',E'Miku');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'1925',E'',E'1925',E'T-POCKET',E'Miku');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'サンドリヨン',E'Cendrillon',E'Cendrillon',E'Signal-P, orange',E'Miku, KAITO');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'スノーマン',E'Snowman',E'Snowman',E'halyosy',E'KAITO');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'骸骨楽団とリリア',E'Gaikotsu Gakudan to Lilia',E'Skeleton Orchestra and Lilia',E'Tohma',E'Miku');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'ありふれたせかいせいふく',E'Arifureta Sekai Seifuku',E'Common World Domination',E'Pinocchio-P',E'Miku');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'インタビュア',E'Interviewer',E'Interviewer',E'Kuwagata-P',E'Luka');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'ピアノ×フォルテ×スキャンダル',E'Piano × Forte × Scandal',E'Piano × Forte × Scandal',E'OSTER project',E'MEIKO');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'shake it!',E'',E'shake it!',E'emon(Tes.)',E'Miku, Rin, Len');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'アカツキアライヴァル',E'Akatsuki Arrival',E'Daybreak Arrival',E'Last Note.',E'Miku, Luka');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'Glory 3usi9',E'',E'Glory 3usi9',E'Hoehoe-P',E'Miku');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'スキキライ',E'Suki Kirai',E'Love-Hate',E'HoneyWorks',E'Rin, Len');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'指切り',E'Yubikiri',E'Pinky Swear',E'Scop',E'Miku');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'Blackjack',E'',E'Blackjack',E'Yucha-P',E'Luka');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'からくりピエロ',E'Karakuri Pierrot',E'Clockwork Clown',E'40mP',E'Miku');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'なりすましゲンガー',E'Narisumashi Genga',E'Doubleganger',E'KulfiQ',E'Rin, Miku');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'こちら、幸福安心委員会です。',E'Kochira, Koufuku Anshin Iinkai desu.',E'This is the Happiness and Peace of Mind Committee',E'Utata-P, Tory Hitsuji',E'Miku');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'Hello, Worker',E'',E'Hello, Worker',E'Hayashikei',E'Luka');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'メテオ',E'Meteor',E'Meteor',E'John',E'Miku');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'soundless voice',E'',E'soundless voice',E'Hitoshizuku-P',E'Len');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'erase or zero',E'',E'erase or zero',E'Crystal-P',E'Len, KAITO');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'エンヴィキャットウォーク',E'Envy Cat Walk',E'Envy Cat Walk',E'Tohma',E'Miku');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'DECORATOR',E'',E'DECORATOR',E'kz',E'Miku');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'二次元ドリームフィーバー',E'Nijigen Dream Fever',E'2D Dream Fever',E'PolyphonicBranch',E'Miku');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'はじめまして地球人さん',E'Hajimemashite Chikyuujin-san',E'Nice to Meet You, Mr. Earthling',E'Pinocchio-P',E'Miku');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'Hand in Hand',E'',E'Hand in Hand',E'kz',E'Miku');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'白い雪のプリンセスは',E'Shiroi Yuki no Princess wa',E'The Snow White Princess is',E'Noboru↑-P',E'Miku');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'39',E'',E'39',E'DECO*27, sasakure.UK',E'Miku');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'ブラックゴールド',E'Black Gold',E'Black Gold',E'otetsu',E'Luka');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'ヒビカセ',E'Hibikase',E'Resonate',E'Giga-P, Reol',E'Miku');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'ゴーストルール',E'Ghost Rule',E'Ghost Rule',E'DECO*27',E'Miku');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'砂の惑星',E'Suna no Wakusei',E'DUNE',E'Hachi',E'Miku');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'The secret garden',E'',E'The secret garden',E'Satoru Kosaki, Aki Hata',E'Miku');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'こっち向いて Baby',E'Kocchi Muite Baby',E'Look This Way, Baby',E'ryo',E'Miku');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'積乱雲グラフィティ',E'Sekiranun Graffiti',E'Cumulonimbus Cloud Graffiti',E'ryo, Dixie Flatline',E'Miku');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'ゆめゆめ',E'YUMEYUME',E'DREAM DREAM',E'DECO*27',E'Miku');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'結ンデ開イテ羅刹ト骸',E'Musunde Hiraite Rasetsu to Mukuro',E'Close and Open, Demons and The Dead',E'Hachi',E'Miku');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'エレクトロサチュレイタ',E'electro saturator',E'electro saturator',E'tilt-six',E'Miku');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'炉心融解',E'Roshin Yuukai',E'Meltdown',E'iroha(sasaki), kuma(alfred)',E'Rin');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'ダブルラリアット',E'Double Lariat',E'Double Lariat',E'Agoaniki-P',E'Luka');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'ハイハハイニ',E'Hai wa Hai ni',E'Ashes to Ashes',E'Tennen, niboshi',E'KAITO');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'壊セ壊セ',E'Kowase Kowase',E'Break It, Break It!',E'E.L.V.N',E'MEIKO');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'初めての恋が終わる時',E'Hajimete no Koi ga Owaru Toki',E'When First Love Ends',E'ryo',E'Miku');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'妄想スケッチ',E'Mousou Sketch',E'Delusion Sketch',E'40mP',E'Miku');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'デンパラダイム',E'Den Paradigm',E'Den Paradigm',E'lumo',E'Miku');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'孤独の果て -extend edition-',E'Kodoku no Hate',E'Solitude\'s End -extend edition-',E'Hikarisyuyo',E'Rin, Len');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'右肩の蝶',E'Migikata no Chou',E'Butterfly on Your Right Shoulder',E'Nori-P, Yura Mizuno',E'Len');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'No Logic',E'',E'No Logic',E'JimmyThumb-P',E'Luka');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'え？あぁ、そう。',E'E? Aa, Sou.',E'Hm? Ah, Yes.',E'Chouchou-P',E'Miku');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'packaged',E'',E'packaged',E'kz',E'Miku');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'巨大少女',E'Kyodai Shoujo',E'Gigantic Girl',E'40mP',E'Miku');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'サマーアイドル',E'Summer Idol',E'Summer Idol',E'OSTER project',E'Miku, Rin');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'千年の独奏歌',E'Sennen no Dokusou Ka',E'Thousand Year Solo',E'yanagi-P',E'KAITO');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'忘却心中',E'Boukyaku Shinjuu',E'Lover\'s Suicide Oblivion',E'OPA, Asaki No\'9',E'MEIKO');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'WORLD\'S END UMBRELLA',E'',E'WORLD\'S END UMBRELLA',E'Hachi',E'Miku');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'恋スルVOC@LOID',E'Koisuru VOC@LOID',E'VOC@LOID in Love',E'OSTER project',E'Miku');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'神曲',E'Kami Kyoku',E'God-Tier Tune',E'Onew-P',E'Miku');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'Yellow',E'',E'Yellow',E'kz',E'Miku');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'ネガポジ＊コンティニューズ',E'Negaposi*Continues',E'Negaposi*Continues',E'sasakure.UK',E'Miku');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'SING&SMILE',E'',E'SING&SMILE',E'Re:nG',E'Miku');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'歌に形はないけれど',E'Uta ni Katachi wa Nai Keredo',E'Though My Song Has No Form',E'doriko',E'Miku');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'Dear',E'',E'Dear',E'19\'s Sound Factory',E'Miku');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'どういうことなの！？',E'Dou Iu Koto na no!?',E'What Do You Mean!?',E'Kuchibashi-P',E'Miku');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'クローバー♣クラブ',E'Clover♣Club',E'Clover♣Club',E'Yuuyu-P',E'Miku');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'リンちゃんなう！',E'Rin-chan Nau!',E'Rin-chan Now!',E'Owata-P, sezu',E'Miku, Luka');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'深海シティアンダーグラウンド',E'Shinkai City Underground',E'Deep Sea City Underground',E'Tanaka-B',E'Rin');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'二息歩行',E'Nisoku Hokou',E'Two Breaths Walking',E'DECO*27',E'Miku');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'PIANO*GIRL',E'',E'PIANO*GIRL',E'OSTER project',E'Miku');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'システマティック・ラヴ',E'Systematic Love',E'Systematic Love',E'Camellia, TENKOMORI',E'Miku');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'ココロ',E'Kokoro',E'Heart',E'Toraboruta-P',E'Rin');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'夢喰い白黒バク',E'Yumekui Shirokuro Baku',E'Dream-Eating Monochrome Baku',E'Nem',E'Len');
insert into songs(name,romanized_name,english_name,artist,vocaloid) values (E'Knife',E'',E'Knife',E'rerulili, mal',E'Rin, Miku, Len');

